apiVersion:
argoproj.io/v1alpha1
kind: Application
metadata:
 name: techtrends-prod
 namespace: argocd
spec:
 destination:
   namespace: default
   server: https://kubernetes.default.svc
 project: default
 source:
   helm:
     valueFiles:
       - values-staging.yaml
   path: helm
   repoURL:
    https://github.com/tech-trends-nd064-course/nd064_course_1
   targetRevision: HEAD