namespace:
  name: prod 
 
service:
  port: 7111
  type: ClusterIP

image:
  repository: remyapadmanabhan/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"