namespace:
  name: staging 
 
image:
  repository: remyapadmanabhan/techtrends
  tag: latest
  pullPolicy: Always
  
service:
  port: 5111
  type: ClusterIP

replicaCount: 3

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"